--修改毒麻处方已经打印过了的记费记录药品,应该上了新功能,所以
SELECT * from BD_OU_DEPT where NAME_DEPT like '%南院麻醉科%'
--目前已经生成的毒麻处方药品
SELECT PK_CGIP,cg.PK_PRES,pi.CODE_IP,pv.NAME_PI ,NAME_CG,DATE_CG,PK_PDSTDT,FLAG_PRT,BATCH_NO from BL_IP_DT cg
  INNER JOIN BD_PD pd on pd.PK_PD = cg.PK_ITEM and DT_POIS in ('01','02','04')
  INNER JOIN PV_ENCOUNTER pv on pv.PK_PV = cg.PK_PV
  INNER JOIN PI_MASTER pi on pi.PK_PI = pv.PK_PI
  INNER JOIN CN_PRESCRIPTION pres on pres.PK_PRES = cg.PK_PRES
where PK_DEPT_CG = '25FBCDEE20414119B632FE34BF6FE328' and FLAG_PD = 1 and cg.PK_PRES is not null and FLAG_PRT  =1

--生成请领明细
--INSERT INTO EX_PD_APPLY_DETAIL
SELECT
  replace(sys_guid(), '-', '') PK_PDAPDT,
  'a41476368e2943f48c32d0cb1179dab8' PK_ORG,
  'd85253039ac641619f5f0ec1e485a724' PK_PDAP,
  --请领单主键
  '1' EU_DIRECT,
  PK_PV,
  PK_PRES,
  PK_CNORD,
  '0' EU_DETYPE,
  '0' FLAG_BASE,
  '0' FLAG_MEDOUT,
  '0' FLAG_SELF,
  PK_PD,
  BATCH_NO,
  PK_UNIT,
  PACK_SIZE,
  QUAN_PACK,
  QUAN_MIN,
  '1' ORDS,
  PRICE_COST,
  PRICE,
  AMOUNT,
  '0' FLAG_DE,
  '0' FLAG_FINISH,
  '0' FLAG_STOP,
  NULL REASON_STOP,
  NULL PK_EMP_STOP,
  NULL NAME_EMP_STOP,
  NULL PK_CGIP,
  'ben0406' CREATOR,
  NULL CREATE_TIME,
  NULL MODIFIER,
  NULL MODITY_TIME,
   '0' DEL_FLAG,
  NULL DATE_EXPIRE,
  NULL TS,
  NULL FLAG_EMER,
  NULL DT_EXDEPTPDSTOP,
  '0' EU_RESULT,
  NULL FLAG_PIVAS,
  NULL NAME_EMP_BACK,
  NULL PK_EMP_BACK,
  NULL DATE_BACK,
  NULL NOTE,
  '0' FLAG_CANC
FROM (SELECT cg.PK_PV,cg.PK_PRES,PK_CNORD,cg.PK_PD,PK_UNIT,cg.PACK_SIZE,QUAN quan_pack,QUAN quan_min,PRICE_COST,cg.PRICE,AMOUNT,BATCH_NO from BL_IP_DT cg
  INNER JOIN BD_PD pd on pd.PK_PD = cg.PK_ITEM and DT_POIS in ('01','02','04')
  INNER JOIN PV_ENCOUNTER pv on pv.PK_PV = cg.PK_PV
  INNER JOIN PI_MASTER pi on pi.PK_PI = pv.PK_PI
  INNER JOIN CN_PRESCRIPTION pres on pres.PK_PRES = cg.PK_PRES
where PK_DEPT_CG = '25FBCDEE20414119B632FE34BF6FE328' and FLAG_PD = 1 and cg.PK_PRES is not null and FLAG_PRT  =1 and PK_PDSTDT is null )

--修改BL_IP_DT的PK_PDSTDT,用于与请领明明细关联
UPDATE BL_IP_DT ipcg
set PK_PDSTDT = (SELECT PK_PDAPDT from
  (SELECT * from EX_PD_APPLY_DETAIL where PK_PDAP = 'd85253039ac641619f5f0ec1e485a724') detail
  INNER JOIN
(SELECT PK_CGIP,cg.PK_PV,cg.PK_PRES,PK_CNORD,cg.PK_PD,PK_UNIT,cg.PACK_SIZE,QUAN quan_pack,QUAN quan_min,PRICE_COST,cg.PRICE,AMOUNT,BATCH_NO from BL_IP_DT cg
  INNER JOIN BD_PD pd on pd.PK_PD = cg.PK_ITEM and DT_POIS in ('01','02','04')
  INNER JOIN PV_ENCOUNTER pv on pv.PK_PV = cg.PK_PV
  INNER JOIN PI_MASTER pi on pi.PK_PI = pv.PK_PI
  INNER JOIN CN_PRESCRIPTION pres on pres.PK_PRES = cg.PK_PRES
where PK_DEPT_CG = '25FBCDEE20414119B632FE34BF6FE328' and FLAG_PD = 1 and cg.PK_PRES is not null and FLAG_PRT  =1 and PK_PDSTDT is null) cg
  ON cg.PK_PRES = detail.PK_PRES and cg.PK_PD = detail.PK_PD where cg.PK_CGIP = ipcg.PK_CGIP)
where exists(SELECT 1 from
  (SELECT * from EX_PD_APPLY_DETAIL where PK_PDAP = 'd85253039ac641619f5f0ec1e485a724') detail
  INNER JOIN
(SELECT PK_CGIP,cg.PK_PV,cg.PK_PRES,PK_CNORD,cg.PK_PD,PK_UNIT,cg.PACK_SIZE,QUAN quan_pack,QUAN quan_min,PRICE_COST,cg.PRICE,AMOUNT,BATCH_NO from BL_IP_DT cg
  INNER JOIN BD_PD pd on pd.PK_PD = cg.PK_ITEM and DT_POIS in ('01','02','04')
  INNER JOIN PV_ENCOUNTER pv on pv.PK_PV = cg.PK_PV
  INNER JOIN PI_MASTER pi on pi.PK_PI = pv.PK_PI
  INNER JOIN CN_PRESCRIPTION pres on pres.PK_PRES = cg.PK_PRES
where PK_DEPT_CG = '25FBCDEE20414119B632FE34BF6FE328' and FLAG_PD = 1 and cg.PK_PRES is not null and FLAG_PRT  =1 and PK_PDSTDT is null) cg
  ON cg.PK_PRES = detail.PK_PRES and cg.PK_PD = detail.PK_PD where  cg.PK_CGIP = ipcg.PK_CGIP);
