SELECT
  POSINO,
  OLDCODE,
  T.NAME,
  SPEC,
  FACTORY,
  UNITPACK,
  SUM(QUANPACK)   QUANPACK,
  SUM(AMOUNTCOST) AMOUNTCOST,
  SUM(AMOUNT)     AMOUNT,
  PRICECOST
FROM
  (SELECT
     --DOC.NAME STTYPE,
     DPS.POSI_NO               ,
     PD.OLD_CODE                 OLDCODE,
     PD.NAME,
     PD.SPEC,
     FACTORY.NAME                FACTORY,
     UNIT.NAME                   UNITPACK,
     EU_DIRECT,
     CASE WHEN ST.EU_DIRECT = '-1'
       THEN QUAN_PACK
     WHEN ST.EU_DIRECT = '1'
       THEN QUAN_PACK * -1 END   QUANPACK,
     --CASE WHEN PD.PACK_SIZE <> 0 THEN PRICE_COST/PD.PACK_SIZE ELSE PRICE_COST END PRICECOST,
     CASE WHEN ST.EU_DIRECT = '-1'
       THEN AMOUNT_COST
     WHEN ST.EU_DIRECT = '1'
       THEN AMOUNT_COST * -1 END AMOUNTCOST,
     CASE WHEN ST.EU_DIRECT = '-1'
       THEN AMOUNT
     WHEN ST.EU_DIRECT = '1'
       THEN AMOUNT * -1 END      AMOUNT,
     --TO_CHAR(ST.DATE_CHK,'YYYY-MM-DD') DATECHK
     PRICE_COST                  PRICECOST
   FROM PD_ST ST
     INNER JOIN PD_ST_DETAIL DT ON ST.PK_PDST = DT.PK_PDST
     INNER JOIN BD_PD PD ON DT.PK_PD = PD.PK_PD
     INNER JOIN BD_FACTORY FACTORY ON FACTORY.PK_FACTORY = PD.PK_FACTORY
     INNER JOIN BD_DEFDOC DOC ON DOC.CODE = ST.DT_STTYPE AND DOC.CODE_DEFDOCLIST = '080008'
     INNER JOIN BD_PD_STORE DPS ON DPS.PK_PD = DT.PK_PD AND DPS.PK_DEPT = '{PKDEPT}'
     INNER JOIN BD_PD_CONVERT CON ON DPS.PK_PDCONVERT = CON.PK_PDCONVERT
     LEFT JOIN BD_UNIT UNIT ON UNIT.PK_UNIT = CON.PK_UNIT
   WHERE {SQL.WHERE("{STTYPE}", " ST.DT_STTYPE IN ({STTYPE}) ")}
          AND {SQL.WHERE("{DATEBEGIN}", "  ST.DATE_CHK >= TO_DATE('{DATEBEGIN} 00:00:00', 'YYYY-MM-DD  HH24:MI:SS') ")}
          AND {SQL.WHERE("{DATEEND}", "  ST.DATE_CHK <= TO_DATE('{DATEEND}  23:59:59', 'YYYY-MM-DD  HH24:MI:SS') ")}
          AND ST.FLAG_CHK='1' AND PK_DEPT_ST = '{USER.PKDEPT}'
   GROUP BY PD.NAME,PD.SPEC, FACTORY.NAME, UNIT.NAME, PD.OLD_CODE, DPS.POSI_NO, PRICE_COST, PD.PACK_SIZE, EU_DIRECT, QUAN_PACK, AMOUNT_COST, AMOUNT, PRICE_COST 
   ORDER BY PD.NAME) T
GROUP BY T.SPEC, FACTORY, UNITPACK, OLDCODE, POSINO, PRICECOST, NAME